### ISSUE TITLE
Alto home page slider

### ISSUE THREAD

**Issue by andrewdefries** [TryGhost/Alto#13]
Hello, 

I would like to have a home page slider as shown in the alto page demo. I activated your theme after installing from casper, but the slider does not show with demo data.

Seen here:

![Screenshot from 2021-01-07 15-04-04](https://user-images.githubusercontent.com/4061566/103939476-d248d780-50f9-11eb-90ff-fd2bf56ab0b4.png)

Can you please advise me how to make said slider using tags as you did.

Many thanks!

**Comment by minimaluminium** [comment]
Hey 👋 . The posts in the slider are populated from the featured posts. If you want them to be from a tag, you can play with the `filter` attribute of the query in `partials/featured.hbs` partial.

We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
