### ISSUE TITLE
Youtube Embed CSS problem

### ISSUE THREAD

**Issue by ayyilmaz** [TryGhost/Alto#14]
Youtube embed is not shown well. The full height of the video is not printed on the page. Half the height of the video is being cut.

test url: https://istihbarat.club/blog/xursudbanu-natavan-kimdir/

![ytbeembed](https://user-images.githubusercontent.com/24845098/104092480-49ff3980-5295-11eb-8c32-62e7be252353.png)

**Comment by minimaluminium** [comment]
Hey @ayyilmaz, there are some custom CSS on your site which looks like they were added through code injection. 

![Screen Shot 2021-01-11 at 10 29 45 AM](https://user-images.githubusercontent.com/1418797/104142824-243e7580-53f8-11eb-832b-8d32bed18edd.png)

FitVids.js (responsive video library) calculates the video ratio and sets `padding-top` style to `.fluid-width-video-wrapper` element. However, the style on your site overrides the style, and that's the reason why the video looks broken.
