### ISSUE TITLE
"Featured" block causes horizontal scrollbar on mobile views

### ISSUE THREAD

**Issue by rozhok** [TryGhost/Alto#16]
Right navigation button overflows over the viewport and causes horizontal scroll spawning. See screenshot.

![image](https://user-images.githubusercontent.com/1721631/107546554-281b0e80-6bd5-11eb-953e-4a5322bd752f.png)

**Comment by minimaluminium** [comment]
Hey @rozhok, thanks for reporting the issue! Fixed this in https://github.com/TryGhost/Alto/commit/01f90ff5303664f6fc24ce3ba2675382ff380651
