### ISSUE TITLE
Multi-line links highlighted incorrectly—only first line is underscored

### ISSUE THREAD

**Issue by rozhok** [TryGhost/Alto#17]
When link word-wrapped to the next line, only the first line is underscored:

![image](https://user-images.githubusercontent.com/1721631/108266936-5cfa0900-7173-11eb-8713-c1a78d8ead59.png)

**Comment by minimaluminium** [comment]
Hey @rozhok, thanks for reporting the issue. Fixed in https://github.com/TryGhost/Alto/commit/50da20bfc2c54dbf4ef6b6cf198a51d6b7d542bf
