### ISSUE TITLE
Format code

### ISSUE THREAD

**Issue by carlostkd** [TryGhost/Alto#23]
Hi on this theme either using markdown or direct insert on the page "```"  and select the code language to format text in code does not works.

**Comment by minimaluminium** [comment]
Hey @carlostkd, sorry about the delay! Code block styling were updated in https://github.com/TryGhost/Alto/commit/393ebaa9f8c68a4eac5f24d89fb6fc53a02def80.

![Screen Shot 2021-03-30 at 12 48 44 PM](https://user-images.githubusercontent.com/1418797/112935619-b08a4a00-9156-11eb-9bdd-0b8229e6c468.png)

On the other hand, if you need syntax highlighting, there's an official [tutorial](https://ghost.org/docs/tutorials/code-syntax-highlighting/) using Prism.js
