### ISSUE TITLE
Unable to integrate with Disqus comment.

### ISSUE THREAD

**Issue by amyuki** [TryGhost/Alto#25]
Disqus comment are working incorrect, it can't loading the current post's comments.

As [https://ghost.org/integrations/disqus/](https://ghost.org/integrations/disqus/) said, there is `this.page.identifier = "ghost-{{comment_id}}"` in the scripts but now {{comment_id}} return nothing.

From Theme Developing Doc [https://ghost.org/docs/themes/contexts/post/](https://ghost.org/docs/themes/contexts/post/) , **{{comment_id}}** must be inside the **{{#post}}** and **{{/post}}** block. But Alto's comment block is outside the post block ([post.hbs](https://github.com/TryGhost/Alto/blob/d96fb318a3e29da76a6617cedf9587b2a8cb6178/post.hbs#L20)). 
Could you help to fixing it? Thanks.

**Comment by reminia** [comment]
This is a bug. You can fix manually by edit post.hbs and put the {{> comment}} right after {{> post-navigation}}.

**Comment by minimaluminium** [comment]
Thanks, fixed in https://github.com/TryGhost/Alto/commit/b2fcb8f697d1378ff1b2afc7c21b8a206af9715b
