### ISSUE TITLE
Disqus Dark Mode - Text Invisible 

### ISSUE THREAD

**Issue by Slethen** [TryGhost/Alto#28]
When the dark mode toggle is enabled Disqus comments aren’t visible, appears Disqus has a dark/light mode but it needs to be manually enabled. Not sure if this is fixable with a CSS override but thought it was worth mentioning as Disqus is Ghosts recommendation for comments.

**Update**
Just noticed it only happens setting changing the mode while on a post page, if the page is loaded in dark mode comments will work, when switched to light they will become the same colour as the background.

Example below. Thanks!

![97006574-6CF4-4920-B79B-E7A59E055AA6](https://user-images.githubusercontent.com/1405445/120724167-24383280-c4cb-11eb-9dc1-09ec4d34e6ee.jpeg)

**Comment by minimaluminium** [comment]
Hey @Slethen,

According to Disqus,

> A light or dark color scheme is automatically selected based on your site's stylesheets.
>
> The light scheme is loaded when the text color Disqus inherits from your site has >= 50% gray contrast: between color: `#000000` and color: `#787878`
>
> The dark scheme is loaded in all other instances.

That means when your site is in dark mode, Disqus will choose its dark mode automatically.

If you're on a single post, and change your site theme from light to dark, Disqus' script would require a refresh to calculate the colors.
