### ISSUE TITLE
Unable to add Disqus

### ISSUE THREAD

**Issue by xe-nvdk** [TryGhost/Alto#29]
Hello folks. I'm trying to get Disqus on the blog following this: https://iveel.co/docs/alto-ghost-theme#section-disqus-comment

The file is not present, so I created one with the data required, but after restart Ghost, the comment box does not appear. I'm missing something?

Thank you
Ignacio

**Comment by minimaluminium** [comment]
Hey @xe-nvdk,

Sorry, that documentation is outdated. To add Disqus, open `/partials/comment.hbs` and add the Disqus embed code between the `<div>`s. Also be sure to comment out the section by removing `{{!--` and `--}}` 🙂
