### ISSUE TITLE
Blogpost tags are low-contrast in dark mode

### ISSUE THREAD

**Issue by mhansen** [TryGhost/Alto#31]
Example: https://alto.ghost.io/company-starts-growing/

The 'STARTUP' tag is barely readable. Looks like the stylesheet just forgot to override the color, as it's the same color as in light mode.

![image](https://user-images.githubusercontent.com/105529/131239836-87c3c161-e18d-4e3a-b49a-339022b93e75.png)

**Comment by minimaluminium** [comment]
Whoops, the primary tag has the accent color as its text color. The demo site was using the default black accent color. Just restored the old accent color. Thanks!

![Screen Shot 2021-08-30 at 6 39 56 PM](https://user-images.githubusercontent.com/1418797/131327541-73bb7a51-e52b-4565-b125-c9198beaa3f7.png)
