### ISSUE TITLE
<li> Bullet points are low-contrast in dark mode

### ISSUE THREAD

**Issue by mhansen** [TryGhost/Alto#32]
Example: https://www.markhansen.co.nz/book-data-oriented-design/

The bullet points are black. I think they should be white: 

![image](https://user-images.githubusercontent.com/105529/131239865-093cd7c2-1831-468e-8e6e-b81a33abde80.png)

Like how the three-dot bullet `<hr>`'s in https://alto.ghost.io/office-interior-inspirations/ turn white in dark mode:
![image](https://user-images.githubusercontent.com/105529/131239874-0301d157-9ed4-4c6f-976a-830241e293d5.png)

**Comment by minimaluminium** [comment]
Whoops, the bullets have the accent color as their background color. The demo site was using the default black accent color. Just restored the old accent color. Thanks!

![Screen Shot 2021-08-30 at 6 39 45 PM](https://user-images.githubusercontent.com/1418797/131327715-88968511-ffb7-4a6a-ae1f-dc2caaa32ce5.png)

**Comment by mhansen** [comment]
Thanks. As feedback, it's tough choosing an accent that works in both day
and night mode, and I didn't even know accent colors were a thing until I
saw them here! Wonder if it would be possible to have defaults that work
for people like me that didn't even know about accent colors...
