### ISSUE TITLE
'Read Now' link is low-contrast in dark mode

### ISSUE THREAD

**Issue by mhansen** [TryGhost/Alto#33]
Example: https://alto.ghost.io/

![image](https://user-images.githubusercontent.com/105529/131239893-9717cf18-5aea-4b81-841b-2851d911c90a.png)

This text should probably be turned gray, just like 'Read Later' has.

**Comment by minimaluminium** [comment]
Whoops, the "Read now" link has the accent color as its text color. The demo site was using the default black accent color. Just restored the old accent color. Thanks!

![Screen Shot 2021-08-30 at 6 40 05 PM](https://user-images.githubusercontent.com/1418797/131327652-c3a182b4-b342-43a8-a054-a4efd4470b4e.png)
