### ISSUE TITLE
Feature Request: Show secondary navigation links

### ISSUE THREAD

**Issue by mhansen** [TryGhost/Alto#37]
https://ghost.org/changelog/secondary-navigation/ documents secondary links.

I tried this on https://www.markhansen.co.nz/ with Alto theme and don't see them anywhere.

**Comment by minimaluminium** [comment]
Hey there! Secondary navigation support has just been added in https://github.com/TryGhost/Alto/commit/d0a23ac9f7b49695efa2cf87a51c09e0a67b4fe5. If there's a secondary navigation, the footer logo will be replaced with the navigation.

**Comment by mhansen** [comment]
Thanks. Do I have to wait for a release / version bump to see this
reflected in ghost pro? It’s still showing version 1.0.0

**Comment by minimaluminium** [comment]
You can simply re-install the theme from the Marketplace which will override the existing one :)

**Comment by mhansen** [comment]
Thank you; I can confirm your fix works (and looks great!) have a good one
