### ISSUE TITLE
Dark mode logo

### ISSUE THREAD

**Issue by uxai** [TryGhost/Alto#40]
I am trying out the Alto theme. From the Ghost UI, there isn't an option to upload the dark-mode compatible logo. Is there some other way to do it without editing the code? Thanks!

**Comment by minimaluminium** [comment]
Hey @uxai, that's a very good point! White logo option was added as a custom setting in https://github.com/TryGhost/Alto/commit/898c73ce2d15da1725d4790e2e74df584111e1ea.
