### ISSUE TITLE
Feature image has sides cropped, can I stop this?

### ISSUE THREAD

**Issue by mhansen** [TryGhost/Alto#41]
### Issue Summary

macOS Chrome on Ghost(Pro) them: alto Version 1.0.0. Not sure if a theme problem or an editor problem.

### To Reproduce

Try to set this image as the feature image
![Copy of Profilepedia](https://user-images.githubusercontent.com/105529/135702252-bd7d3f6a-a4be-4795-9f5c-0ec001d586b3.png)

It looks good in the editor:

![image](https://user-images.githubusercontent.com/105529/135702312-f86de3b4-01f0-403d-bb9c-2d8d7799a13b.png)

Preview the blog:
![image](https://user-images.githubusercontent.com/105529/135702284-7bf9dabf-68f0-4d52-b5fc-c1d4e35acd6f.png)

1. The sides are cut off
2. It has a gray background. Not sure why? This is probably a theme bug because if changes with night mode.

Expected: sides not cut off.

### Technical details:

* Ghost Version: Whatever's on GhostPro right now.

**Comment by minimaluminium** [comment]
Hey @mhansen,

Sorry about the delay! This is theme specific design which crops the images to ration of 1:2. I understand that it's not suitable for diagram type images. You can change this behavior by adding this CSS in `Settings > Code inject > Site Header`.

```html
<style>
    .post-feed .post-image,
    .single-post .post-image {
        position: static;
    }
    
    .post-feed .post-media .u-placeholder::before,
    .single-post .post-media .u-placeholder::before {
    	display: none;
    }
</style>
```
