### ISSUE TITLE
How to pin a featured post to top of home page on alto

### ISSUE THREAD

**Issue by xilou31** [TryGhost/Alto#44]
I have searched the internet, but didn't find the answer.

**Comment by xilou31** [comment]
On the internet, it seems to modify some files like index.hbs, but I followed this step and it didn't work.

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
