### ISSUE TITLE
Needs jquery.fitvids for embedded YouTube videos

### ISSUE THREAD

**Issue by tdominey** [TryGhost/Alto#46]
The Casper theme has this, but Alto does not. Embedded YouTube videos in Alto appear square when embedded and not at their natural, 16:9 aspect ratio.

**Comment by minimaluminium** [comment]
Alto has [Reframe.js](https://dollarshaveclub.github.io/reframe.js/) which is a jQuery-free alternative for FitVids. And it supports YouTube, Vimeo and Kickstarter videos. Would you be able to send the video URL?

**Comment by tdominey** [comment]
Ah...that explains it. I was modifying the theme and didn't use built/main.min.js. Closing...
