### ISSUE TITLE
Pinterest share button has a design bug

### ISSUE THREAD

**Issue by kymellis** [TryGhost/Alto#5]
<img width="855" alt="Screenshot 2020-10-21 at 16 23 26" src="https://user-images.githubusercontent.com/16795687/96701514-e6165480-13ba-11eb-9967-1830a7284174.png">

Here's what it looks like on kymellis.co

**Comment by minimaluminium** [comment]
Fixed in https://github.com/TryGhost/Alto/commit/c69702dca43668f518d56513c2e0bf914f389a1c :)
