### ISSUE TITLE
Dark Mode kg-bookmark

### ISSUE THREAD

**Issue by Slethen** [TryGhost/Alto#6]
kg-bookmark title & content should use the white colour variable in dark mode.

I tried adding them to dark.css which didn't work, I wasn't totally sure on how the dark-mode worked.

![image](https://user-images.githubusercontent.com/1405445/97981111-b6f3e000-1dc9-11eb-8116-97d50159fd74.png)

Thanks!

**Comment by minimaluminium** [comment]
Hey @Slethen, thanks for that! Fixed in https://github.com/TryGhost/Alto/commit/32acac045fa00daccd2c3d5b7b0a0c5ab841b8a9. You can also see that working on the page [Style Guide](https://alto.ghost.io/style-guide/) of the demo.

**Comment by Slethen** [comment]
Fantastic! Thanks so much @minimaluminium. Updated my blog 😊
