### ISSUE TITLE
Can I make a list of tags on a page?

### ISSUE THREAD

**Issue by gaolingxiao** [TryGhost/Alto#7]
How to make a list of tags on a page? Or it is not available yet? Thanks.

**Comment by koznov** [comment]
+1 here

I was trying to use instruction https://blog.many-monkeys.com/adding-a-tags-page-to-ghost-blog/ but stuck because there is no site-nav.hbs file in theme.

Maybe there is any method to create custom tag page with all tags on site?

**Comment by gaolingxiao** [comment]
> +1 here
> 
> I was trying to use instruction https://blog.many-monkeys.com/adding-a-tags-page-to-ghost-blog/ but stuck because there is no site-nav.hbs file in theme.
> 
> Maybe there is any method to create custom tag page with all tags on site?

I think this theme hasn't supported this feature yet. We can write our own tags page, but it needs a little bit of coding.

**Comment by minimaluminium** [comment]
@gaolingxiao We don't have any page for listing tags on our themes. There are numbers of tutorials for this topic which users can follow and include on their sites.

@koznov The important part of the tutorial is the following section which loops through the available tags and outputs them with post counts.

```hbs
{{#get 'tags' limit='all' include='count.posts' order='count.posts desc'}}
    {{#foreach tags}}
        {{!-- The tag below includes the markup for each tag - partials/tag-card.hbs --}}
        {{> "tag-card"}}
    {{/foreach}}
{{/get}}
```

`site-nav.hbs` isn't something that is mandatory. For example, you can copy `page.hbs` to `page-tags.hbs` (as in the tutorial) and replace `{{#post}}{{/post}}` part with the code above.

**Comment by ayyilmaz** [comment]
Why you don't add authors and tags pages by default although it is not complex? I think this will make more funtional this theme. Does it effect SEO?
